name: Auto Proxy Scraper

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every hour
  workflow_dispatch:     # Manual trigger

jobs:
  scrape-proxies:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install aiohttp
    
    - name: Run advanced proxy scraper
      run: python proxy_scraper.py
    
    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update proxies [$(date +'%Y-%m-%d %H:%M')]"
        git push
