name: Auto Proxy Scraper

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape-proxies:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    permissions:
      contents: write  # This is crucial
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Add this line
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run proxy scraper
      run: python proxy_scraper.py
    
    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.txt
        git commit -m "Auto-update proxies [$(date +'%Y-%m-%d %H:%M')]"
        git push
